### ISSUE TITLE
add `py.typed` marker in order to be compatible with PEP 561

### ISSUE THREAD

**Issue by amirsoroush** [ManiMozaffar/aioclock#19]
Thanks for your great, well-written library.

Currently for people like me who have their Pylance's type checking mode set to strict, there is warning which says:

<img width="752" alt="image" src="https://github.com/ManiMozaffar/aioclock/assets/114881632/c1733080-8ec0-4cf0-87fb-a7a097d56568">

By adding a file named `py.typed` in the root of the project the problem will be gone:

From [PEP 561](https://peps.python.org/pep-0561/#packaging-type-information):

> Package maintainers who wish to support type checking of their code MUST add a marker file named `py.typed` to their package supporting typing.

I also think that this should be added in pyproject.toml file:

```
[tool.setuptools.package-data]
"aioclock" = ["py.typed"]
```

---

Also two tiny typos:

1. in line:

https://github.com/ManiMozaffar/aioclock/blob/main/aioclock/app.py#L229

it should be `task` actually, instead of `group`.

2. In the red note of the page https://manimozaffar.github.io/aioclock/latest/api/external_api/:

> But this is a bit tricky and implicit because then your code gets ignored and **"database"** is preferred over the **"database"**

the second one should be codebase I guess.

**Comment by ManiMozaffar** [comment]
Thanks for the issue. I'll make the adjustment later. You can also do a PR if you wish to.
